<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.ruml.ecommerce</groupId>
        <artifactId>ruml-backend-core-inventory</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>
    <artifactId>ruml-backend-core-inventory-usecase</artifactId>
    
    <dependencies>
        <dependency>
            <groupId>com.ruml.ecommerce</groupId>
            <artifactId>ruml-backend-core-shared-usecase</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.ruml.ecommerce</groupId>
            <artifactId>ruml-backend-core-inventory-entity</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.ruml.ecommerce</groupId>
            <artifactId>ruml-backend-core-inventory-port</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.ruml.ecommerce</groupId>
            <artifactId>ruml-backend-core-inventory-factory</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>
</project>
