<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.ruml.ecommerce</groupId>
        <artifactId>ruml-backend-presentation</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>
    <artifactId>ruml-backend-presentation-controller-main</artifactId>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>com.ruml.ecommerce</groupId>
            <artifactId>ruml-backend-presentation-controller-auth</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.ruml.ecommerce</groupId>
            <artifactId>ruml-backend-presentation-controller-store</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.ruml.ecommerce</groupId>
            <artifactId>ruml-backend-presentation-controller-perfume</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.ruml.ecommerce</groupId>
            <artifactId>ruml-backend-presentation-controller-order</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.ruml.ecommerce</groupId>
            <artifactId>ruml-backend-presentation-controller-support</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.ruml.ecommerce</groupId>
            <artifactId>ruml-backend-presentation-controller-audit</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.ruml.ecommerce</groupId>
            <artifactId>ruml-backend-presentation-controller-shared</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.ruml.ecommerce</groupId>
            <artifactId>ruml-backend-presentation-security-filter-jwt</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.ruml.ecommerce</groupId>
            <artifactId>ruml-backend-presentation-spring-context</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.ruml.ecommerce</groupId>
            <artifactId>ruml-backend-core-shared-executor-impl</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.ruml.ecommerce</groupId>
            <artifactId>ruml-backend-core-auth-dao-jpa</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.ruml.ecommerce</groupId>
            <artifactId>ruml-backend-core-store-dao-jpa</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.ruml.ecommerce</groupId>
            <artifactId>ruml-backend-core-perfume-dao-jpa</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.ruml.ecommerce</groupId>
            <artifactId>ruml-backend-core-order-dao-jpa</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.ruml.ecommerce</groupId>
            <artifactId>ruml-backend-core-support-dao-jpa</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.ruml.ecommerce</groupId>
            <artifactId>ruml-backend-core-audit-dao-jpa</artifactId>
            <version>${project.version}</version>
        </dependency>
    
        <dependency>
            <groupId>org.liquibase</groupId>
            <artifactId>liquibase-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
